<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-MediaConverter-e392a3a7-5025-460e-91d4-666388fb4c0e</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CloudConvert.API" Version="1.4.0" />
    <PackageReference Include="FFMpegCore" Version="5.4.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DAL\" />
    <Folder Include="Files\" />
    <Folder Include="MediaExamples\" />
  </ItemGroup>
</Project>
